name: Test suite

on:
  workflow_dispatch:
  pull_request:
    branches:
      - develop
      - master
    paths:
      - .github/workflows/testsuite.yml
      - segmetrics/*.py
      - setup.py
      - tests/*.py
      - tests/*.csv
      - requirements.txt
  push:
    branches:
      - master

jobs:
  python_lint:
    name: Linting
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort

      - name: Run flake8
        shell: bash
        run: |
          flake8 segmetrics
          flake8 tests

      - name: Run isort
        shell: bash
        run: |
          isort segmetrics --check-only
          isort tests --check-only

  type_checking:
    name: Type checking
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mypy

      - name: Run mypy
        shell: bash
        run: |
          mypy --config-file .mypy.ini --ignore-missing-imports segmetrics

  run_testsuite:
    uses: BMCV/github-workflows/.github/workflows/coverage-run.yml@main
    name: Tests
    with:
      apt_install: libopenblas-dev
      main_branch: master
      python_versions: '["3.9", "3.10", "3.11", "3.12"]'
      main_python_version: "3.9"
      gist-id: f46ddefff0798639bc320b13331dc7ca
      gist-filename: segmetrics.json
      run: |
        coverage run -m unittest discover
        python -m coverage json --omit "tests/*,segmetrics/deprecated.py"
    secrets:
      gist-auth: ${{ secrets.GIST_SECRET }}
